version: "3"

networks:
  todo:

services:
  mysql:
    image: coney/mysql:5
    deploy:
      replicas: 1
      restart_policy:
        delay: 10s
    networks:
      todo:
        aliases:
        - mysql
    ports:
    - "3306:3306"
  zuul_gateway:
      image: chensen/zuul-gateway:${VER}
      deploy:
        replicas: 2
        restart_policy:
          delay: 10s
      depends_on:
      - mysql
      networks:
        todo:
          aliases:
          - zuul-gateway
      ports:
      - "8080:8080"
      environment:
      - SPRING_PROFILES_ACTIVE=default