server:
  port: 8080
#  context-path: /api
#
#spring:
#  application:
#    name: gateway
#  cloud:
#    consul:
#      host: consul
#      port: 8500
#      discovery:
#        instanceId: ${spring.application.name}:${random.int}

userservice:
  ribbon:
    listOfServers: localhost:8081
#    , localhost:8001


todoservice:
  ribbon:
    listOfServers: localhost:8082
#    , localhost:8002

zuul:
  sensitiveHeaders:
  routes:
    reister-service:
      path: /users
      serviceId: userservice
      strip-prefix: false
#    ignored-service:
#      path: /login
#      url: http://localhost:8081
#      strip-prefix: false
    todo-service:
      path: /todos
      serviceId: todoservice
      strip-prefix: false
  prefix: /api


logging:
  level:
    org:
      springframework:
        cloud:
          netflix: TRACE